from torchvision import tv_tensors as tvt
from torchvision.transforms.v2 import (
    JPEG,
    RGB,
    AugMix,
    AutoAugment,
    AutoAugmentPolicy,
    CenterCrop,
    ColorJitter,
    Compose,
    CutMix,
    ElasticTransform,
    FiveCrop,
    GaussianBlur,
    GaussianNoise,
    Grayscale,
    Identity,
    Lambda,
    LinearTransformation,
    MixUp,
    Normalize,
    Pad,
    RandAugment,
    RandomAdjustSharpness,
    RandomAffine,
    RandomApply,
    RandomAutocontrast,
    RandomChannelPermutation,
    RandomChoice,
    RandomCrop,
    RandomEqualize,
    RandomErasing,
    RandomGrayscale,
    RandomHorizontalFlip,
    RandomInvert,
    RandomIoUCrop,
    RandomOrder,
    RandomPerspective,
    RandomPhotometricDistort,
    RandomPosterize,
    RandomResize,
    RandomResizedCrop,
    RandomRotation,
    RandomShortestSize,
    RandomSolarize,
    RandomVerticalFlip,
    RandomZoomOut,
    Resize,
    SanitizeBoundingBoxes,
    ScaleJitter,
    TenCrop,
    ToDtype,
    Transform,
    TrivialAugmentWide,
)


def default_transform() -> Transform:
    return Compose(
        [
            Resize((800, 800)),
            RandomHorizontalFlip(),
        ]
    )
