site_name: pytorchcocotools
repo_url: https://github.com/twsl/pytorchcocotools
repo_name: twsl/pytorchcocotools
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2024 twsl

nav:
  - Home: index.md
  - API: $api/pytorchcocotools.***
  - Examples: notebooks/index.md

theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.action.edit
    # - content.action.view
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - toc.follow
  font:
    text: Roboto
  palette:
    - media: "(prefers-color-scheme)"
      primary: black
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css: # fix ui bug in material theme/mkapi
  - styles/extra.css

extra:
  generator: false

plugins:
  - search
  - mkdocs-jupyter
  - mkapi
  - awesome-pages
  - tags
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: false
      type: iso_datetime

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - github-callouts
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: false

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
